export const SEARCH_FOR_MOVIES = 'SEARCH_FOR_MOVIES';
export const SELECT_MOVIE = 'SELECT_MOVIE';
export const SEARCH_FOR_TOP_RATED_MOVIES = 'SEARCH_FOR_TOP_RATED_MOVIES';
export const SEARCH_FOR_MOVIE = 'SEARCH_FOR_MOVIE';
export const FETCH_GENRES = 'FETCH_GENRES';
export const SEARCH_FOR_MOVIES_BY_QUERY = 'SEARCH_FOR_MOVIES_BY_QUERY';
